import { Metadata } from "next";
import styles from "./AdminPage.module.scss";
import AdminNavigation from "@/components/AdminNavigation/AdminNavigation";

export const metadata: Metadata = {
  title: "Quasar | Управление",
  description: "Generated by create next app",
};

export default function ProfileLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className={styles["admin"]}>
      <AdminNavigation />
      {children}
    </section>
  );
}
