import { FC } from "react";
import "./RegisterPage.scss";
import RegisterForm from "@/components/AuthForm/RegisterForm";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Quasar | Регистрация",
  description: "Generated by create next app",
};

const RegisterPage: FC = () => {
  return (
    <div className="auth-page">
      <h1 className="title auth-page__title">Регистрация</h1>
      <RegisterForm />
    </div>
  );
};

export default RegisterPage;
