import Navbar from "@/components/Navbar/Navbar";
import "./globals.scss";
import type { Metadata } from "next";
import MainProvider from "@/components/MainProvider/MainProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="main">
          <div className="container">
            <MainProvider>
              <Navbar />
              {children}
            </MainProvider>
          </div>
        </main>
      </body>
    </html>
  );
}
