import ProfileNavigation from "@/components/ProfileNavigation/ProfileNavigation";
import { Metadata } from "next";
import "./ProfilePage.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ProfileLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="profile">
      <ProfileNavigation />
      {children}
    </section>
  );
}
