import { FC } from "react";
import "./LoginPage.scss";
import LoginForm from "@/components/AuthForm/LoginForm";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Quasar | Авторизация",
  description: "Generated by create next app",
};

const LoginPage: FC = () => {
  return (
    <div className="auth-page">
      <h1 className="title auth-page__title">Авторизация</h1>
      <LoginForm />
    </div>
  );
};

export default LoginPage;
